.PHONY: clean All

All:
	@echo "----------Building project:[ SmartPointerWeakPointer - Debug ]----------"
	@cd "SmartPointerWeakPointer" && "$(MAKE)" -f  "SmartPointerWeakPointer.mk"
clean:
	@echo "----------Cleaning project:[ SmartPointerWeakPointer - Debug ]----------"
	@cd "SmartPointerWeakPointer" && "$(MAKE)" -f  "SmartPointerWeakPointer.mk" clean
