.PHONY: clean All

All:
	@echo "----------Building project:[ PolymorphismSectionChallenge - Debug ]----------"
	@cd "PolymorphismSectionChallenge" && "$(MAKE)" -f  "PolymorphismSectionChallenge.mk"
clean:
	@echo "----------Cleaning project:[ PolymorphismSectionChallenge - Debug ]----------"
	@cd "PolymorphismSectionChallenge" && "$(MAKE)" -f  "PolymorphismSectionChallenge.mk" clean
