.PHONY: clean All

All:
	@echo "----------Building project:[ Variable - Debug ]----------"
	@cd "Variable" && "$(MAKE)" -f  "Variable.mk"
clean:
	@echo "----------Cleaning project:[ Variable - Debug ]----------"
	@cd "Variable" && "$(MAKE)" -f  "Variable.mk" clean
